WaterCtrl_v1: Logging
Logging
Communication
Detailed Description
Enumerations
enum LogLevel { LogError = 0x01, LogInfo = 0x02, LogDebug = 0x04 }
enum LogDestination { LogDstSerConsole = 0x01, LogDstRaspberryPi = 0x02 }
Functions
void Log (LogLevel loglevel, const char *format,...)
Do logging.
void LogUart (LogLevel loglevel, const char *format,...)
Do logging explicit on UART, not SPI.
void logSetDestination (LogDestination destination)
Set log desftination.
void logSetFilter (LogLevel filter)
Set log filter.
Enumeration Type Documentation
enum LogDestination
these are the possible log destinations
Definition at line 24 of file log.h.
enum LogLevel
these are the log levels for message
Definition at line 21 of file log.h.
Function Documentation
void Log (LogLevel loglevel, const char * format, ...)
Do logging.
Parameters
loglevel The loglevel of enum type LogLevel
format message to send, printf style formatting
Definition at line 25 of file log.c.
References printf(), spiSend(), and vsprintf().
Referenced by HAL_SPI_TxRxCpltCallback(), initScheduler(), MeasureInit(), and WatchdogStart().
void logSetDestination (LogDestination destination)
Set log desftination.
Parameters
destination The log destination as enum type of LogDestination
Definition at line 92 of file log.c.
void logSetFilter (LogLevel filter)
Set log filter.
Parameters
filter The log filter as enum type of LogDestination
Definition at line 96 of file log.c.
void LogUart (LogLevel loglevel, const char * format, ...)
Do logging explicit on UART, not SPI.
Parameters
loglevel The loglevel of enum type LogLevel
format message to send, printf style formatting
Definition at line 67 of file log.c.
References printf(), and vsprintf().
Referenced by SPIrecvProc(), and spiSend().