WaterCtrl_v1: Printf
Printf
RetargetPrintf
Detailed Description
Macros
#define MAX_STRING_SIZE STR_MAX_SIZE
Functions
__attribute__ ((weak))
Transmit a char, if you want to use printf(), you need implement this function.
signed int PutChar (char *pStr, char c)
Writes a character inside the given string. Returns 1.
signed int PutString (char *pStr, const char *pSource)
Writes a string inside the given string.
signed int PutUnsignedInt (char *pStr, char fill, signed int width, unsigned int value)
Writes an unsigned int inside the given string, using the provided fill & width parameters.
signed int PutSignedInt (char *pStr, char fill, signed int width, signed int value)
Writes a signed int inside the given string, using the provided fill & width parameters.
signed int PutHexa (char *pStr, char fill, signed int width, unsigned char maj, unsigned int value)
Writes an hexadecimal value into a string, using the given fill, width & capital parameters.
signed int vsnprintf (char *pStr, size_t length, const char *pFormat, va_list ap)
Stores the result of a formatted string into another string. Format arguments are given in a va_list instance.
signed int snprintf (char *pString, size_t length, const char *pFormat,...)
Stores the result of a formatted string into another string. Format arguments are given in a va_list instance.
signed int vsprintf (char *pString, const char *pFormat, va_list ap)
Stores the result of a formatted string into another string. Format arguments are given in a va_list instance.
signed int vfprintf (FILE *pStream, const char *pFormat, va_list ap)
Outputs a formatted string on the given stream. Format arguments are given in a va_list instance.
signed int vprintf (const char *pFormat, va_list ap)
Outputs a formatted string on the DBGU stream. Format arguments are given in a va_list instance.
signed int fprintf (FILE *pStream, const char *pFormat,...)
Outputs a formatted string on the given stream, using a variable number of arguments.
signed int printf (const char *pFormat,...)
Outputs a formatted string on the DBGU stream, using a variable number of arguments.
signed int sprintf (char *pStr, const char *pFormat,...)
Writes a formatted string inside another string.
signed int puts (const char *pStr)
Outputs a string on stdout.
signed int fputc (signed int c, FILE *pStream)
Implementation of fputc using the DBGU as the standard output. Required for printf().
signed int fputs (const char *pStr, FILE *pStream)
Implementation of fputs using the DBGU as the standard output. Required for printf().
Variables
struct _reent r = {0, (FILE *) 0, (FILE *) 1, (FILE *) 0}
struct _reent * _impure_ptr = &r
Macro Definition Documentation
#define MAX_STRING_SIZE STR_MAX_SIZE
Maximum string size allowed (in bytes).
Definition at line 34 of file printf.c.
Referenced by vfprintf(), and vsprintf().
Function Documentation
__attribute__ ((weak))
Transmit a char, if you want to use printf(), you need implement this function.
Parameters
pStr Storage string.
c Character to write.
Definition at line 25 of file printf.c.
signed int fprintf (FILE * pStream, const char * pFormat, ...)
Outputs a formatted string on the given stream, using a variable number of arguments.
Parameters
pStream Output stream.
pFormat Format string.
Definition at line 448 of file printf.c.
References vfprintf().
signed int fputc (signed int c, FILE * pStream)
Implementation of fputc using the DBGU as the standard output. Required for printf().
Parameters
c Character to write.
pStream Output stream.
The character written if successful, or -1 if the output stream is not stdout or stderr.
Definition at line 522 of file printf.c.
Referenced by fputs().
signed int fputs (const char * pStr, FILE * pStream)
Implementation of fputs using the DBGU as the standard output. Required for printf().
Parameters
pStr String to write.
pStream Output stream.
Returns
Number of characters written if successful, or -1 if the output stream is not stdout or stderr.
Definition at line 547 of file printf.c.
References fputc().
Referenced by puts(), and vfprintf().
signed int printf (const char * pFormat, ...)
Outputs a formatted string on the DBGU stream, using a variable number of arguments.
Parameters
pFormat Format string.
Definition at line 468 of file printf.c.
References vprintf().
signed int PutChar (char * pStr, char c)
Writes a character inside the given string. Returns 1.
Parameters
pStr Storage string.
c Character to write.
Definition at line 47 of file printf.c.
Referenced by PutHexa(), PutSignedInt(), PutUnsignedInt(), and vsnprintf().
signed int PutHexa (char * pStr, char fill, signed int width, unsigned char maj, unsigned int value)
Writes an hexadecimal value into a string, using the given fill, width & capital parameters.
Parameters
pStr Storage string.
fill Fill character.
width Minimum integer width.
maj Indicates if the letters must be printed in lower- or upper-case.
value Hexadecimal value.
Returns
The number of char written
Definition at line 209 of file printf.c.
References PutChar().
Referenced by vsnprintf().
signed int puts (const char * pStr)
Outputs a string on stdout.
Parameters
pStr String to output.
Definition at line 507 of file printf.c.
References fputs().
signed int PutSignedInt (char * pStr, char fill, signed int width, signed int value)
Writes a signed int inside the given string, using the provided fill & width parameters.
Parameters
pStr Storage string.
fill Fill character.
width Minimum integer width.
value Signed integer value.
Definition at line 130 of file printf.c.
References PutChar().
Referenced by vsnprintf().
signed int PutString (char * pStr, const char * pSource)
Writes a string inside the given string.
Parameters
pStr Storage string.
pSource Source string.
Returns
The size of the written
Definition at line 61 of file printf.c.
Referenced by vsnprintf().
signed int PutUnsignedInt (char * pStr, char fill, signed int width, unsigned int value)
Writes an unsigned int inside the given string, using the provided fill & width parameters.
Parameters
pStr Storage string.
fill Fill character.
width Minimum integer width.
value Integer value.
Definition at line 84 of file printf.c.
References PutChar().
Referenced by vsnprintf().
signed int snprintf (char * pString, size_t length, const char * pFormat, ...)
Stores the result of a formatted string into another string. Format arguments are given in a va_list instance.
Parameters
pStr Destination string.
length Length of Destination string.
pFormat Format string.
... Other arguments
Returns
The number of characters written.
Definition at line 374 of file printf.c.
References vsnprintf().
signed int sprintf (char * pStr, const char * pFormat, ...)
Writes a formatted string inside another string.
Parameters
pStr torage string.
pFormat Format string.
Definition at line 488 of file printf.c.
References vsprintf().
signed int vfprintf (FILE * pStream, const char * pFormat, va_list ap)
Outputs a formatted string on the given stream. Format arguments are given in a va_list instance.
Parameters
pStream Output stream.
pFormat Format string
ap Argument list.
Definition at line 411 of file printf.c.
References fputs(), MAX_STRING_SIZE, and vsprintf().
Referenced by fprintf(), and vprintf().
signed int vprintf (const char * pFormat, va_list ap)
Outputs a formatted string on the DBGU stream. Format arguments are given in a va_list instance.
Parameters
pFormat Format string.
ap Argument list.
Definition at line 435 of file printf.c.
References vfprintf().
Referenced by printf().
signed int vsnprintf (char * pStr, size_t length, const char * pFormat, va_list ap)
Stores the result of a formatted string into another string. Format arguments are given in a va_list instance.
Parameters
pStr Destination string.
length Length of Destination string.
pFormat Format string.
ap Argument list.
Returns
The number of characters written.
Definition at line 273 of file printf.c.
References PutChar(), PutHexa(), PutSignedInt(), PutString(), and PutUnsignedInt().
Referenced by snprintf(), and vsprintf().
signed int vsprintf (char * pString, const char * pFormat, va_list ap)
Stores the result of a formatted string into another string. Format arguments are given in a va_list instance.
Parameters
pString Destination string.
length Length of Destination string.
pFormat Format string.
ap Argument list.
Returns
The number of characters written.
Definition at line 398 of file printf.c.
References MAX_STRING_SIZE, and vsnprintf().
Referenced by sprintf(), and vfprintf().
Variable Documentation
struct _reent r = {0, (FILE *) 0, (FILE *) 1, (FILE *) 0}
Required for proper compilation.
Definition at line 38 of file printf.c.