WaterCtrl_v1: MoistureMeasure
MoistureMeasure
Detailed Description
Macros
#define PERI_PRESCALAR 2
#define TIMER_PRESCALAR 10
#define TIMER_CLOCK SystemCoreClock/(PERI_PRESCALAR*TIMER_PRESCALAR)
#define IC_SAMPLE_FILTER 0x02u
#define MOISTURE_SENS_PIN_A0 GPIO_PIN_1
#define MOISTURE_SENS_PORT_A0 GPIOB
#define MOISTURE_SENS_PIN_A1 GPIO_PIN_10
#define MOISTURE_SENS_PORT_A1 GPIOB
#define MOISTURE_SENS_PIN_A2 GPIO_PIN_11
#define MOISTURE_SENS_PORT_A2 GPIOB
#define MOISTURE_SENS_PIN_ENABLE GPIO_PIN_15
#define MOISTURE_SENS_PORT_ENABLE GPIOB
#define MOISTURE_MEASURE_CHANNEL_MAX 0x08u
#define MOISTURE_MEASURE_STATE_INACTIVE 0x0000
#define MOISTURE_MEASURE_STATE_ACTIVE 0x0001
#define MOISTURE_MEASURE_CHANNEL0_ACTIVE 0
#define MOISTURE_MEASURE_CHANNEL1_ACTIVE 1
#define MOISTURE_MEASURE_CHANNEL2_ACTIVE 2
#define MOISTURE_MEASURE_CHANNEL3_ACTIVE 3
#define MOISTURE_MEASURE_CHANNEL4_ACTIVE 4
#define MOISTURE_MEASURE_CHANNEL5_ACTIVE 5
#define MOISTURE_MEASURE_CHANNEL6_ACTIVE 6
#define MOISTURE_MEASURE_CHANNEL7_ACTIVE 7
Functions
uint32_t getFrequencyOfChannel ()
Get ISR's data.
void resetFrequencyOfChannel ()
uint32_t getCapture ()
void HAL_TIM_IC_CaptureCallback (TIM_HandleTypeDef *htim)
This function handles TIM1 Capture Compare interrupt request.
int MeasureInit (TIM_HandleTypeDef *ptrTimerRef, uint32_t channel)
Starts Timer and enables interrupt.
void EnableMeasureInterrupt ()
Enable timer interrupt.
void DisableMeasureInterrupt ()
Disable timer interrupt.
int startSensorCapture (int channel)
Starts Timer and enables interrupt.
void moiDisableSensor ()
void moiEnableSensor ()
void moiSetChannel (int)
uint_fast64_t getMoisture ()
int initMoistureMeasure (TIM_HandleTypeDef *ptr)
void printMoisture ()
void MoistureTask ()
int deinitMoistureMeasure (void)
Variables
volatile uint32_t IC3ReadValue1 = 0
volatile uint32_t IC3ReadValue2 = 0
volatile uint32_t CaptureNumber = 0
volatile uint32_t Capture = 0
volatile uint32_t TIM1Freq = 0
volatile uint32_t frequency [MOISTURE_MEASURE_CHANNEL_MAX]
uint16_t stateRegister = MOISTURE_MEASURE_STATE_INACTIVE
uint activeChannel = 0
TIM_HandleTypeDef * ptrTimer3Ref
uint32_t Timer3Channel
Function Documentation
uint32_t getFrequencyOfChannel ()
Get ISR's data.
See also
isr_moisture.c
Definition at line 28 of file isr_moisture.c.
int MeasureInit (TIM_HandleTypeDef * ptrTimerRef, uint32_t channel)
Starts Timer and enables interrupt.
Parameters
ptrTimerRef Timer to use
channel Channel to use
Return values
return value
Definition at line 160 of file moistureMeasure.c.
References EnableMeasureInterrupt(), and Log().
Referenced by startSensorCapture().
int startSensorCapture (int channel)
Starts Timer and enables interrupt.
Parameters
ptrTimerRef Timer to use
channel Channel to use
Return values
return value
Definition at line 133 of file moistureMeasure.c.
References MeasureInit().